//AGREGAR PRODUCTOS
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

//MOSTRAR PRODUCTOS
export const DESCARGA_PRODUCTOS = 'DESCARGA_PRODUCTOS'
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO'
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR'


//ELIMINAR PRODUCTOS
export const ELIMINAR_PRODUCTOS = 'ELIMINAR_PRODUCTOS'
export const ELIMINAR_PRODUCTOS_EXITO = 'ELIMINAR_PRODUCTOS_EXITO'
export const ELIMINAR_PRODUCTOS_ERROR = 'ELIMINAR_PRODUCTOS_ERROR'


//EDITAR PRODUCTOS
export const EDITAR_PRODUCTOS = 'EDITAR_PRODUCTOS'
export const GUARDAR_EDITAR_PRODUCTOS = 'GUARDAR_EDITAR_PRODUCTOS'
export const EDITAR_PRODUCTOS_EXITO = 'EDITAR_PRODUCTOS_EXITO'
export const EDITAR_PRODUCTOS_ERROR = 'EDITAR_PRODUCTOS_ERROR'
